Project2WooxTravel/Areas/Admin/Controllers/AdminLayoutController.cs
using Project2WooxTravel.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project2WooxTravel.Areas.Admin.Controllers
{
    public class AdminLayoutController : Controller
    {
        TravelContext context = new TravelContext();
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult PartialHead()
        {
            return PartialView();
        }
        public PartialViewResult PartialSideBar()
        {
            return PartialView();
        }
        public PartialViewResult PartialNavbar()
        {
            var username = Session["user"];
            var value = context.Admins.Where(x => x.Username == username).FirstOrDefault();

            return PartialView(value);
        }
        public PartialViewResult PartialMessageNavbar()
        {
            var username = Session["user"];
            var email = context.Admins.Where(x => x.Username == username).Select(y => y.Email).FirstOrDefault();
            var incomingEmails = context.Messages.Where(x => x.ReceiverMail == email).ToList();
            var incomingEmailsCount = context.Messages.Where(x => x.ReceiverMail == email).Count();

            ViewBag.MessageCount = incomingEmailsCount;
            return PartialView(incomingEmails);
        }

        public ActionResult PartialDestinationNavbar()
        {
            var last4Destination = context.Destinations.OrderByDescending(d => d.DestinationId).Take(4).ToList();

            return PartialView(last4Destination);
        }
        public PartialViewResult PartialFooter()
        {
            return PartialView();
        }
        public PartialViewResult PartialScript()
        {
            return PartialView();
        }
    }
}

Project2WooxTravel/Areas/Admin/Controllers/ReservationController.cs
using PagedList;
using Project2WooxTravel.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project2WooxTravel.Areas.Admin.Controllers
{
    public class ReservationController : Controller
    {
        TravelContext context = new TravelContext();
        public ActionResult ReservationList(int page = 1)
        {

            int pageSize = 5;
            var reservations = context.Reservations.OrderBy(x => x.ReservationId).ToPagedList(page, pageSize);

            return View(reservations);
        }
    }
}

Project2WooxTravel/Areas/Admin/Views/AdminLayout/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
@Html.Action("PartialHead", "AdminLayout", "Admin")
<body>
    <div class="wrapper">

        @Html.Action("PartialSideBar", "AdminLayout", "Admin")


        @Html.Action("PartialNavbar", "AdminLayout", "Admin")

        @RenderBody()

        @Html.Action("PartialFooter", "AdminLayout", "Admin")

    </div>

    @Html.Action("PartialScript", "AdminLayout", "Admin")

</body>
</html>

Project2WooxTravel/Areas/Admin/Views/AdminLayout/PartialDestinationNavbar.cshtml
@model List<Project2WooxTravel.Entities.Destination>

<li class="nav-item topbar-icon dropdown hidden-caret">
    <a class="nav-link dropdown-toggle"
       href="#"
       id="notifDropdown"
       role="button"
       data-bs-toggle="dropdown"
       aria-haspopup="true"
       aria-expanded="false">
        <i class="fa fa-road"></i>
    </a>
    <ul class="dropdown-menu notif-box animated fadeIn"
        aria-labelledby="notifDropdown">
        <li>
            <div class="dropdown-title">
                Son Eklenen Rotalar
            </div>
        </li>
        <li>
            @{
                string GetTimeAgo(DateTime sendDate)
                {
                    var timeSpan = DateTime.Now - sendDate;

                    if (timeSpan.TotalSeconds < 60)
                        return $"{(int)timeSpan.TotalSeconds} saniye önce";
                    if (timeSpan.TotalMinutes < 60)
                        return $"{(int)timeSpan.TotalMinutes} dakika önce";
                    if (timeSpan.TotalHours < 24)
                        return $"{(int)timeSpan.TotalHours} saat önce";
                    if (timeSpan.TotalDays < 30)
                        return $"{(int)timeSpan.TotalDays} gün önce";
                    if (timeSpan.TotalDays < 365)
                        return $"{(int)(timeSpan.TotalDays / 30)} ay önce";

                    return $"{(int)(timeSpan.TotalDays / 365)} yıl önce";
                }
            }
            <div class="notif-scroll scrollbar-outer">
                <div class="notif-center">
                    @foreach (var item in Model)
                    {
                        <a href="#">
                            <div class="notif-icon notif-primary">
                                <i class="fa fa-user-plus"></i>
                            </div>
                            <div class="notif-content">
                                <span class="block"> @item.Title </span>
                                <span class="time">@GetTimeAgo(item.CreatedAt)</span>
                            </div>
                        </a>
                    }
                </div>
            </div>
        </li>
        <li>
            <a class="see-all" href="/Default/Index/">
                Tüm Rotaları Gör <i class="fa fa-angle-right"></i>
            </a>
        </li>
    </ul>
</li>

Project2WooxTravel/Areas/Admin/Views/AdminLayout/PartialFooter.cshtml
<footer class="footer">
    <div class="container-fluid d-flex justify-content-between">
        <nav class="pull-left">
        </nav>
        <div class="copyright">
            @DateTime.Now.Year <i class="fa fa-heart heart text-danger"></i>
            <a href="/Default/Index/">WoOx Travel</a>
        </div>
        <div>
        </div>
    </div>
</footer>

Project2WooxTravel/Areas/Admin/Views/AdminLayout/PartialHead.cshtml
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Woox Travel Admin Paneli</title>
    <meta content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
          name="viewport" />
    <link rel="icon"
          href="/kaiadmin-lite-1.2.0/assets/img/kaiadmin/favicon.ico"
          type="image/x-icon" />

    <!-- Fonts and icons -->
    <script src="/kaiadmin-lite-1.2.0/assets/js/plugin/webfont/webfont.min.js"></script>
    <script>
        WebFont.load({
            google: { families: ["Public Sans:300,400,500,600,700"] },
            custom: {
                families: [
                    "Font Awesome 5 Solid",
                    "Font Awesome 5 Regular",
                    "Font Awesome 5 Brands",
                    "simple-line-icons",
                ],
                urls: ["/kaiadmin-lite-1.2.0/assets/css/fonts.min.css"],
            },
            active: function () {
                sessionStorage.fonts = true;
            },
        });</script>

    <!-- CSS Files -->
    <link rel="stylesheet" href="/kaiadmin-lite-1.2.0/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/kaiadmin-lite-1.2.0/assets/css/plugins.min.css" />
    <link rel="stylesheet" href="/kaiadmin-lite-1.2.0/assets/css/kaiadmin.min.css" />

    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link rel="stylesheet" href="/kaiadmin-lite-1.2.0/assets/css/demo.css" />
</head>

Project2WooxTravel/Areas/Admin/Views/AdminLayout/PartialMessageNavbar.cshtml
@model List<Project2WooxTravel.Entities.Message>

<li class="nav-item topbar-icon dropdown hidden-caret">
    <a class="nav-link dropdown-toggle"
       href="#"
       id="messageDropdown"
       role="button"
       data-bs-toggle="dropdown"
       aria-haspopup="true"
       aria-expanded="false">
        <i class="fa fa-envelope"></i>
        <span class="notification">@ViewBag.MessageCount</span>
    </a>
    <ul class="dropdown-menu messages-notif-box animated fadeIn"
        aria-labelledby="messageDropdown">
        <li>
            <div class="dropdown-title d-flex justify-content-between align-items-center">
                Mesajlar
            </div>
        </li>
        <li>
            @{
                string GetTimeAgo(DateTime sendDate)
                {
                    var timeSpan = DateTime.Now - sendDate;

                    if (timeSpan.TotalSeconds < 60)
                        return $"{(int)timeSpan.TotalSeconds} saniye önce";
                    if (timeSpan.TotalMinutes < 60)
                        return $"{(int)timeSpan.TotalMinutes} dakika önce";
                    if (timeSpan.TotalHours < 24)
                        return $"{(int)timeSpan.TotalHours} saat önce";
                    if (timeSpan.TotalDays < 30)
                        return $"{(int)timeSpan.TotalDays} gün önce";
                    if (timeSpan.TotalDays < 365)
                        return $"{(int)(timeSpan.TotalDays / 30)} ay önce";

                    return $"{(int)(timeSpan.TotalDays / 365)} yıl önce";
                }
            }
            <div class="message-notif-scroll scrollbar-outer">
                <div class="notif-center">
                    @foreach (var item in Model)
                    {
                        <a href="#">
                            <div class="notif-img">
                                <img src="https://i.hizliresim.com/468qqmy.png"
                                     alt="Envelope" />
                            </div>
                            <div class="notif-content">
                                <span class="subject">@item.SenderMail</span>
                                <span class="block"> @item.Subject </span>
                                <span class="time">@GetTimeAgo(item.SendDate)</span>
                            </div>
                        </a>
                    }
                </div>
            </div>
        </li>
        <li>
            <a class="see-all" href="/Admin/Message/Inbox/">
                Tüm Mesajları Gör <i class="fa fa-angle-right"></i>
            </a>
        </li>
    </ul>
</li>

Project2WooxTravel/Areas/Admin/Views/AdminLayout/PartialNavbar.cshtml
@model Project2WooxTravel.Entities.Admin

<div class="main-panel">
    <div class="main-header">
        <div class="main-header-logo">
            <!-- Logo Header -->
            <div class="logo-header" data-background-color="dark">
                <a href="../index.html" class="logo">
                    <img src="../assets/img/kaiadmin/logo_light.svg"
                         alt="navbar brand"
                         class="navbar-brand"
                         height="20" />
                </a>
                <div class="nav-toggle">
                    <button class="btn btn-toggle toggle-sidebar">
                        <i class="gg-menu-right"></i>
                    </button>
                    <button class="btn btn-toggle sidenav-toggler">
                        <i class="gg-menu-left"></i>
                    </button>
                </div>
                <button class="topbar-toggler more">
                    <i class="gg-more-vertical-alt"></i>
                </button>
            </div>
            <!-- End Logo Header -->
        </div>
        <!-- Navbar Header -->
        <nav class="navbar navbar-header navbar-header-transparent navbar-expand-lg border-bottom">
            <div class="container-fluid">
                <nav class="navbar navbar-header-left navbar-expand-lg navbar-form nav-search p-0 d-none d-lg-flex">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <button type="submit" class="btn btn-search pe-1">
                                <i class="fa fa-search search-icon"></i>
                            </button>
                        </div>
                        <input type="text"
                               placeholder="Aranacak Kelime ..."
                               class="form-control" />
                    </div>
                </nav>

                <ul class="navbar-nav topbar-nav ms-md-auto align-items-center">
                    <li class="nav-item topbar-icon dropdown hidden-caret d-flex d-lg-none">
                        <a class="nav-link dropdown-toggle"
                           data-bs-toggle="dropdown"
                           href="#"
                           role="button"
                           aria-expanded="false"
                           aria-haspopup="true">
                            <i class="fa fa-search"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-search animated fadeIn">
                            <form class="navbar-left navbar-form nav-search">
                                <div class="input-group">
                                    <input type="text"
                                           placeholder="Search ..."
                                           class="form-control" />
                                </div>
                            </form>
                        </ul>
                    </li>
                    @Html.Action("PartialMessageNavbar", "AdminLayout")
                    @Html.Action("PartialDestinationNavbar", "AdminLayout")
                    <li class="nav-item topbar-user dropdown hidden-caret">
                        <a class="dropdown-toggle profile-pic"
                           data-bs-toggle="dropdown"
                           href="#"
                           aria-expanded="false">
                            <div class="avatar-sm">
                                <img src="https://t4.ftcdn.net/jpg/02/29/75/83/360_F_229758328_7x8jwCwjtBMmC6rgFzLFhZoEpLobB6L8.jpg"
                                     alt="..."
                                     class="avatar-img rounded-circle" />
                            </div>
                            <span class="profile-username">
                                <span class="op-7">Merhaba,</span>
                                @*<span class="fw-bold">@Model.Name</span>*@
                            </span>
                        </a>
                        <ul class="dropdown-menu dropdown-user animated fadeIn">
                            <div class="dropdown-user-scroll scrollbar-outer">
                            <li>
                                <div class="user-box">
                                    <div class="avatar-lg">
                                        <img src="https://t4.ftcdn.net/jpg/02/29/75/83/360_F_229758328_7x8jwCwjtBMmC6rgFzLFhZoEpLobB6L8.jpg"
                                             alt="image profile"
                                             class="avatar-img rounded" />
                                    </div>
                                    <div class="u-text">
                                        @*<h4>@Model.Name @Model.Surname</h4>
                                        <p class="text-muted">@Model.Email</p>*@
                                        <a href="/Admin/Profile/"
                                           class="btn btn-xs btn-secondary btn-sm">Profili Gör</a>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="/Admin/Profile/">Profilim</a>
                                <a class="dropdown-item" href="/Admin/Message/Inbox">Gelen Kutusu</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="/Login/LogOut">Çıkış Yap</a>
                            </li>
            </div>
            </ul>
            </li>
            </ul>
    </div>
    </nav>
    <!-- End Navbar -->
</div>

Project2WooxTravel/Areas/Admin/Views/AdminLayout/PartialScript.cshtml
<!--   Core JS Files   -->
<script src="/kaiadmin-lite-1.2.0/assets/js/core/jquery-3.7.1.min.js"></script>
<script src="/kaiadmin-lite-1.2.0/assets/js/core/popper.min.js"></script>
<script src="/kaiadmin-lite-1.2.0/assets/js/core/bootstrap.min.js"></script>

<!-- jQuery Scrollbar -->
<script src="/kaiadmin-lite-1.2.0/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
<!-- Kaiadmin JS -->
<script src="/kaiadmin-lite-1.2.0/assets/js/kaiadmin.min.js"></script>
<!-- Kaiadmin DEMO methods, don't include it in your project! -->
<script src="/kaiadmin-lite-1.2.0/assets/js/setting-demo2.js"></script>
<script>
    $("#displayNotif").on("click", function () {
        var placementFrom = $("#notify_placement_from option:selected").val();
        var placementAlign = $("#notify_placement_align option:selected").val();
        var state = $("#notify_state option:selected").val();
        var style = $("#notify_style option:selected").val();
        var content = {};

        content.message =
            'Turning standard Bootstrap alerts into "notify" like notifications';
        content.title = "Bootstrap notify";
        if (style == "withicon") {
            content.icon = "fa fa-bell";
        } else {
            content.icon = "none";
        }
        content.url = "index.html";
        content.target = "_blank";

        $.notify(content, {
            type: state,
            placement: {
                from: placementFrom,
                align: placementAlign,
            },
            time: 1000,
        });
    });</script>

Project2WooxTravel/Areas/Admin/Views/AdminLayout/PartialSideBar.cshtml
<div class="sidebar" data-background-color="dark">
    <div class="sidebar-logo">
        <!-- Logo Header -->
        <div class="logo-header" data-background-color="dark">
            <a href="~/kaiadmin-lite-1.2.0/index.html" class="logo">
                <img src="~/kaiadmin-lite-1.2.0/assets/img/kaiadmin/logo_light.svg"
                     alt="navbar brand"
                     class="navbar-brand"
                     height="20" />
            </a>
            <div class="nav-toggle">
                <button class="btn btn-toggle toggle-sidebar">
                    <i class="gg-menu-right"></i>
                </button>
                <button class="btn btn-toggle sidenav-toggler">
                    <i class="gg-menu-left"></i>
                </button>
            </div>
            <button class="topbar-toggler more">
                <i class="gg-more-vertical-alt"></i>
            </button>
        </div>
        <!-- End Logo Header -->
    </div>
    <div class="sidebar-wrapper scrollbar scrollbar-inner">
        <div class="sidebar-content">
            <ul class="nav nav-secondary">
                <li class="nav-item">
                    <a href="/Admin/Dashboard/Index/"
                       class="collapsed"
                       aria-expanded="false">
                        <i class="fas fa-home"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li class="nav-section">
                    <span class="sidebar-mini-icon">
                        <i class="fa fa-ellipsis-h"></i>
                    </span>
                    <h4 class="text-section">İşlemler</h4>
                </li>
                <li class="nav-item">
                    <a data-bs-toggle="collapse" href="#category">
                        <i class="fas fa-layer-group"></i>
                        <p>Kategori</p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse" id="category">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="@Url.Action("CategoryList", "Category")">
                                    <span class="sub-item">Kategori Listesi</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("CreateCategory", "Category")">
                                    <span class="sub-item">Kategori Ekle</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a data-bs-toggle="collapse" href="#destination">
                        <i class="fas fa-road"></i>
                        <p>Destinasyon</p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse" id="destination">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="@Url.Action("DestinationList", "Destination")">
                                    <span class="sub-item">Destinasyon Listesi</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("CreateDestination", "Destination")">
                                    <span class="sub-item">Destinasyon Ekle</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a data-bs-toggle="collapse" href="#reservation">
                        <i class="fas fa-calendar"></i>
                        <p>Rezervasyon</p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse" id="reservation">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="@Url.Action("ReservationList", "Reservation")">
                                    <span class="sub-item">Rezervasyon Listesi</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="nav-section">
                    <span class="sidebar-mini-icon">
                        <i class="fa fa-ellipsis-h"></i>
                    </span>
                    <h4 class="text-section">Mesajlar</h4>
                </li>
                <li class="nav-item">
                    <a href="/Admin/Message/Inbox/"
                       class="collapsed"
                       aria-expanded="false">
                        <i class="fas fa-inbox"></i>
                        <p>Gelen Mesajlar</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="/Admin/Message/Sendbox/"
                       class="collapsed"
                       aria-expanded="false">
                        <i class="fas fa-paper-plane"></i>
                        <p>Gönderilen Mesajlar</p>
                    </a>
                </li>
                <li class="nav-section">
                    <span class="sidebar-mini-icon">
                        <i class="fa fa-ellipsis-h"></i>
                    </span>
                    <h4 class="text-section">Grafikler</h4>
                </li>
                <li class="nav-item">
                    <a href="/Admin/Chart/Line/"
                       class="collapsed"
                       aria-expanded="false">
                        <i class="fas fa-chart-line"></i>
                        <p>Çizgi Grafiği</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="/Admin/Chart/Bar/"
                       class="collapsed"
                       aria-expanded="false">
                        <i class="fas fa-chart-area"></i>
                        <p>Bar Grafiği</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="/Admin/Chart/Pie/"
                       class="collapsed"
                       aria-expanded="false">
                        <i class="fas fa-chart-pie"></i>
                        <p>Pasta Grafiği</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="/Admin/Chart/Doughnut/"
                       class="collapsed"
                       aria-expanded="false">
                        <i class="far fa-circle"></i>
                        <p>Donut Grafiği</p>
                    </a>
                </li>
                <li class="nav-section">
                    <span class="sidebar-mini-icon">
                        <i class="fa fa-ellipsis-h"></i>
                    </span>
                    <h4 class="text-section">Ödeme Yöntemi</h4>
                </li>
                <li class="nav-item">
                    <a href="/Admin/CreditCard/Index/"
                       class="collapsed"
                       aria-expanded="false">
                        <i class="fas fa-credit-card"></i>
                        <p>Kredi Kartı</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>